### PR TITLE
add SpringDamper component

### PR DESCRIPTION
**Pull request by baggepinnen**

### CODE REVIEW

**Comment by baggepinnen** [comment]
test failures unrelated, the added test passes

**Comment by baggepinnen** [comment]
That error has been there for a long time, it's related to a initialization system bug

**Comment by baggepinnen** [comment]
This was the last time tests passed for MTKstdlib, they have never passed on MTKv9
image

**Comment by ChrisRackauckas** [comment]
Is there an "initialization bug" for it? What's the report on it?

**Comment by baggepinnen** [comment]
> Is there an "initialization bug" for it? What's the report on it?

Not sure, it looks like you were the one who merged the PR that broke the tests?

**Comment by baggepinnen** [comment]
https://github.com/SciML/ModelingToolkitStandardLibrary.jl/issues/328

**Pull request merged**
