### PR TITLE
allow the user to override the default smoothing parameter for sources

### PR DESCRIPTION
**Pull request by baggepinnen**

### CODE REVIEW

**Comment by ven-k** [comment]
Changes LGTM.

But wouldn't it be better if
1. We have dispatches based on smooth - Int or Bool?
Or
2. Just have another var `δ` or `smooth_coef``

**Comment by baggepinnen** [comment]
1. You cannot dispatch on keyword arguments, and the workaround to do so makes the code very bloated
2. I didn't want two different arguments to handle the same thing, both of which must be set to achieve a change in smoothness factor
3. I don't want to break the existing interface. 

I think this solution was a good tradeoff

**Review by ven-k — APPROVED** [review]

**Comment by jebej** [comment]
Doesn’t this change make those functions type unstable when `smooth::Bool`?

**Comment by baggepinnen** [comment]
They do, but the output is a symbolical expression, which is type unstable anyways so what does it matter?

**Pull request merged**
