### PR TITLE
Adds input/output meta data

### PR DESCRIPTION
**Pull request by ValentinKaisermayer**
Removes pesky warnings that the connector contains (non-flow, non-stream, non-input, non-output) variables but no flow variable.

### CODE REVIEW

**Review by baggepinnen — APPROVED** [review]

**Comment by ValentinKaisermayer** [comment]
Can we please separate the irreducability from the inputs?
It can not be that this simple system with one state has five states in MTK.

```julia
@named c = Constant(; k=2)
@named gain = Gain(1;)
@named int = Integrator(; k=1)
@named fb = Feedback(;)
@named model = ODESystem(
    [
        connect(c.output, fb.input1), 
        connect(fb.input2, int.output), 
        connect(fb.output, gain.input),
        connect(gain.output, int.input),
    ], 
    t, 
    systems=[int, gain, c, fb]
)
sys = structural_simplify(model)

julia> sys
Model model with 5 equations
States (5):
  int₊x(t) [defaults to 0.0]
  int₊input₊u(t) [defaults to 0.0]
  gain₊input₊u(t) [defaults to 0.0]
⋮
Parameters (3):
  int₊k [defaults to 1]
  gain₊k [defaults to 1]
  c₊k [defaults to 2]
Incidence matrix:5×6 SparseArrays.SparseMatrixCSC{Num, Int64} with 10 stored entries:
 ×  ⋅  ×  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ×
 ⋅  ×  ⋅  ⋅  ×  ⋅
 ⋅  ⋅  ⋅  ×  ×  ×
 ⋅  ⋅  ×  ×  ⋅  ⋅
```

@YingboMa

**Comment by baggepinnen** [comment]
The input should only be considered irreducible `if !is_bound(state)`

**Comment by ValentinKaisermayer** [comment]
> The input should only be considered irreducible `if !is_bound(state)`

https://github.com/SciML/ModelingToolkit.jl/blob/fd279c0377da50331fe920d6dd62f2816e60b02d/src/variables.jl#L30

**Comment by ValentinKaisermayer** [comment]
https://github.com/SciML/ModelingToolkit.jl/issues/1577

**Pull request merged**
