### PR TITLE
fixes Symbolics deprecation

### PR DESCRIPTION
**Pull request by ValentinKaisermayer**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Bump the symbolics lower bound?

**Comment by ValentinKaisermayer** [comment]
Seems to be an MTK issue with `inputs_to_parameters!`
@baggepinnen

**Comment by ValentinKaisermayer** [comment]
Why doesn't the downstream test fail in MTK?

**Review by YingboMa — APPROVED** [review]

**Comment by ValentinKaisermayer** [comment]
> Seems like a real failure?

Yes, but in MTK.

**Review by YingboMa — APPROVED** [review]

**Pull request merged**
